version: '3'
services:
  webapp:
    restart: always
    build: .
    volumes:
      - .:/django-vue.js-docker_sample
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8888"
    ports:
      - "80:8888"