# Generated by Django 4.1.2 on 2022-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_test_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='visibility',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='free_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visibility',
            field=models.CharField(default='private', max_length=20),
        ),
    ]
