# Generated by Django 3.2.16 on 2022-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_test_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
