# Generated by Django 4.0.6 on 2022-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_test_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='visibility',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
