# Generated by Django 3.2.16 on 2022-10-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_test_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(default='理科', max_length=255),
        ),
    ]
