# Generated by Django 3.2.16 on 2022-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_alter_test_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
