# Generated by Django 4.1.3 on 2022-11-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_alter_test_visibility'),
        ('test', '0008_alter_test_subject'),
    ]

    operations = [
    ]
